(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var kGa=function(a){a=String(a);var b=a.indexOf(".");-1==b&&(b=a.length);return(0,g.wBa)("0",Math.max(0,2-b))+a},lGa=function(){return{G:"svg",
T:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},R:[{G:"path",T:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},mGa=function(){return{G:"svg",
T:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},R:[{G:"path",T:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},x3=function(a){"number"===typeof a?(this.date=nGa(a,0,1),w3(this,1)):g.Na(a)?(this.date=nGa(a.getFullYear(),a.getMonth(),a.getDate()),w3(this,a.getDate())):(this.date=new Date(g.A()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),w3(this,a))},nGa=function(a,b,c){b=new Date(a,b,c);
0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b},w3=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},y3=function(a,b){g.NO.call(this,a,{G:"div",
L:"ytp-reminder-menu",T:{role:"menu",tabindex:"-1"},R:[{G:"div",L:"ytp-reminder-menu-contents",R:[{G:"div",L:"ytp-reminder-menu-items"}]}]},100,!0);this.u=b;this.C=[];this.menuPopupRenderer=void 0;this.items=this.ha("ytp-reminder-menu-items");this.hide()},pGa=function(a){var b=oGa(a),c=0,d={};
for(c=0;c<b.length;d={mw:d.mw},c++){var e=a.C[c];e||(e=new g.U({G:"div",L:"ytp-reminder-menu-item",T:{role:"menuitem",tabindex:"0"},R:[{G:"div",L:"ytp-reminder-menu-item-icon",ba:"{{icon}}"},{G:"div",L:"ytp-reminder-menu-item-label",ba:"{{text}}"}]}),d.mw=c,e.ya("click",function(l){return function(){var m=l.mw;a.jb();m=oGa(a)[m];a.V("reminderMenuItemClicked",m.serviceEndpoint||m.command)}}(d)),e.fa(a.items),a.C[c]=e);
var f=b[c],h=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":h=lGa();break;case "NOTIFICATIONS_NONE":h=mGa();break;case "NOTIFICATIONS_ACTIVE":h=g.YL()}f=f.text?g.S(f.text):"";e.update({icon:h,text:f})}for(;c<a.C.length;)a.C.pop().dispose();0===c?a.jb():a.Ec(a.u)},oGa=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},z3=function(a){g.U.call(this,{G:"div",
R:[{G:"button",ia:["ytp-offline-slate-button","ytp-button"],R:[{G:"div",L:"ytp-offline-slate-button-icon",ba:"{{icon}}"},{G:"div",L:"ytp-offline-slate-button-text",ba:"{{text}}"}]}]});this.J=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.B=void 0;this.D=this.u=null;(this.F=this.ha("ytp-offline-slate-button"))&&this.P(this.F,"click",this.I);this.hide()},qGa=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=b.toggleButtonRenderer:
b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&c.upcomingEventReminderButtonRenderer?a.upcomingEventReminderButtonRenderer=c.upcomingEventReminderButtonRenderer:c&&c.upcomingEventReminderButtonRenderer||(a.upcomingEventReminderButtonRenderer=null);A3(a)},A3=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.S(b.toggledText):"";a.update({text:c,icon:B3(b.toggledIcon)})}else c=b.defaultText?g.S(b.defaultText):"",a.update({text:c,icon:B3(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=rGa(a))?(c=b.text?g.S(b.text):"",a.update({text:c,icon:B3(b.icon)}),a.show()):a.hide():a.hide()},tGa=function(a,b,c){a.D||(a.D=new g.Ts(a.J.S().ga));
var d=g.Np(a.D.u||g.Op());g.fu()&&(d.context.clientScreenNonce=g.fu());d.params=c;g.Qp(a.D,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.B&&(a.upcomingEventReminderButtonRenderer.currentState=a.B,a.B=void 0)},
onError:function(){sGa(a)},
onTimeout:function(){sGa(a)}})},sGa=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,A3(a)):a.upcomingEventReminderButtonRenderer&&(a.B=void 0,A3(a))},B3=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return lGa();case "NOTIFICATIONS_NONE":return mGa();case "NOTIFICATIONS_ACTIVE":return g.YL();default:return null}},rGa=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.B||a.upcomingEventReminderButtonRenderer.currentState;a=g.q(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=c.value.upcomingEventReminderButtonStateRenderer)&&c.state===b&&c.button&&c.button.buttonRenderer)return c.button.buttonRenderer;return null},C3=function(a){g.U.call(this,{G:"div",
L:"ytp-offline-slate",R:[{G:"div",L:"ytp-offline-slate-background"},{G:"div",L:"ytp-offline-slate-bar",R:[{G:"span",L:"ytp-offline-slate-icon",R:[{G:"svg",T:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},R:[{G:"path",T:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{G:"circle",T:{cx:"12",cy:"12",r:"3"}}]}]},{G:"span",L:"ytp-offline-slate-messages",R:[{G:"div",L:"ytp-offline-slate-main-text",ba:"{{maintext}}"},{G:"div",L:"ytp-offline-slate-subtitle-text",ba:"{{subtitletext}}"}]},{G:"span",L:"ytp-offline-slate-buttons"}]},{G:"button",ia:["ytp-offline-slate-close-button","ytp-button"],R:[g.TL()]},{G:"button",ia:["ytp-offline-slate-open-button","ytp-button"],R:[g.SL()]},{G:"div",L:"ytp-offline-slate-trailer-chip",ba:"\uc608\uace0\ud3b8"}]});var b=this;this.api=
a;this.B=this.u=null;this.background=this.ha("ytp-offline-slate-background");this.D=this.ha("ytp-offline-slate-bar");this.F=new g.E(function(){g.J(b.D,"ytp-offline-slate-bar-fade")},15E3);
this.I=!1;this.C=new g.E(function(){g.J(b.element,"ytp-offline-slate-collapsed")},15E3);
g.C(this,this.C);g.C(this,this.F);this.countdownTimer=new g.E(this.LH,1E3,this);this.P(a,"presentingplayerstatechange",this.OH);this.P(a,"livestatedata",this.na);a=this.ha("ytp-offline-slate-close-button");this.P(a,"click",function(){g.J(b.element,"ytp-offline-slate-collapsed")});
a=this.ha("ytp-offline-slate-open-button");this.P(a,"click",function(){g.xn(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.na(a)},D3=function(a,b,c){if(b){var d=null!=b.subtitleText?g.S(b.subtitleText):"";
b=c?c:null!=b.mainText?g.S(b.mainText):"";a.getVideoData();a.update({maintext:b,subtitletext:d});g.K(a.element,"ytp-offline-slate-single-text-line",!d)}},E3=function(a,b){var c=(0,g.M)();
this.trigger=a;this.u=b;this.C=c},G3=function(a){g.hO.call(this,a);
var b=this;this.K=!1;this.N=0;this.F=!1;this.B=new g.E(function(){var e=b.player.S(),f=b.getVideoData();if(F3(b))if(uGa(b)){var h;null!==(h=b.heartbeatParams)&&void 0!==h&&h.url&&(e=g.Nd(b.heartbeatParams.url,{request_id:g.Yt()}),f.X&&(e=g.Nd(e,{vvt:f.X}),f.mdxEnvironment&&(e=g.Nd(e,{mdx_environment:f.mdxEnvironment}))),f.oauthToken&&(e=g.Nd(e,{access_token:f.oauthToken})),vGa(b,f,e))}else wGa(b,e,f)},0);
this.u=this.heartbeatParams=null;this.C=!1;this.I=new g.Jn(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.U=new g.Ts(void 0);this.utcOffsetMinutes=-(new x3).date.getTimezoneOffset();this.D=new g.YN(this);g.C(this,this.B);g.C(this,this.D);xGa(this);this.D.P(a,"heartbeatparams",this.GL);this.D.P(a,"presentingplayerstatechange",this.HL);this.D.P(a,"videoplayerreset",this.IL);this.D.P(a,g.tG("heartbeat"),this.yd);this.C&&this.u&&yGa(this,this.u);var c=new g.qG(1E3,0x7ffffffffffff,{priority:0,
namespace:"heartbeat"}),d=new g.qG(0x8000000000000,0x8000000000000,{id:"stream_end",priority:0,namespace:"heartbeat"});a.Jd([c,d])},uGa=function(a){var b=a.getVideoData();
return!g.RI(a.getVideoData())||b.uH?!1:g.P(a.player.S().experiments,"use_innertube_hearbeats_for_playready")?!!b.I&&"widevine"===b.I.flavor:!0},H3=function(a){return uGa(a)?!!a.heartbeatParams:!!a.getVideoData().heartbeatToken},I3=function(a,b){if(!a.B.isActive()&&a.K){var c=a.getVideoData();
if(H3(a)||c.isLivePlayback){if(void 0===b){if(a.F){var d;c=a.C?7500:(null===(d=a.heartbeatParams)||void 0===d?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().tG||6E4}else c=1E3;b=c}a.B.start(b)}}},vGa=function(a,b,c){b.Rh&&(c=g.Nd(c,{internalipoverride:b.Rh}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.Aa&&(d.kpt=b.Aa);c=g.Nd(c,d);g.vq(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.B.isActive()&&F3(a)){a.I.reset();a.sequenceNumber++;e=e.responseText;var f=zGa(e);if(f){a.player.va("onHeartbeat",f);var h="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else h=(h=e.match(AGa))?"0"===h[1]?0:1:-1;BGa(a,f,e,h)}},
onError:function(e){F3(a)&&J3(a,!0,"net-"+e.status)},
onTimeout:function(){F3(a)&&J3(a,!0,"timeout")},
withCredentials:!0})},F3=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.T(a.player.Va(a.getPlayerType()),4)?!1:H3(a)||b.isLivePlayback?!0:(K3(a),!1)},wGa=function(a,b,c){var d={videoId:c.videoId,
sequenceNumber:a.sequenceNumber},e=g.jL();null==e.user&&(e.user={});null==e.request&&(e.request={});c.mdxEnvironment&&(e.request.mdxEnvironment=c.mdxEnvironment);c.Aa&&(e.user.kidsParent={oauthToken:c.Aa});b.enableSafetyMode&&(e.user.enableSafetyMode=!0);c.X&&(e.user.credentialTransferTokens=[{token:c.X,scope:"VIDEO"}]);var f=b.deviceParams,h=b.ga,l={utcOffsetMinutes:a.utcOffsetMinutes};b.experiments.experimentIds&&(l.experimentIds=b.experiments.experimentIds.map(Number));f&&(l.deviceMake=f.cbrand||
"www",l.deviceModel=f.cmodel||"www",l.browserName=f.cbr,l.browserVersion=f.cbrver,l.osName=f.cos,l.osVersion=f.cosver);h&&(l.clientName=h.ju,l.clientVersion=h.innertubeContextClientVersion,l.hl=h.Ly,l.gl=h.Ky);b.homeGroupInfo&&(l.homeGroupInfo=JSON.parse(b.homeGroupInfo));if(f=b.deviceParams.ctheme)l.theme=f;if(f="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)l.timeZone=f;b.livingRoomAppMode&&(l.tvAppInfo={livingRoomAppMode:b.livingRoomAppMode});e.client=l;c.contextParams&&
(l=c.contextParams)&&(e.activePlayers=[],e.activePlayers.push({playerContextParams:l}));d.context=e;d.cpn=c.clientPlaybackNonce;e={heartbeatChecks:[]};if(l=c.getPlayerResponse())d.heartbeatToken=c.heartbeatToken,(l=l.playabilityStatus)&&(l=l.liveStreamability)&&l.liveStreamabilityRenderer&&e.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&e.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");g.QD(b)&&(e.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED"),c.U&&(d.context.client.unpluggedLocationInfo=
c.U),d.context.client.unpluggedAppInfo={enableFilterMode:c.Dj},(b=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(b)&&(l={},l.clientPlayerPositionUtcMillis=""+Math.floor(1E3*b),e.unpluggedParams=l));d.heartbeatRequestParams=e;b={timeout:3E4,onSuccess:function(m){if(!a.B.isActive()&&F3(a)){var n=m.playabilityStatus,p=JSON.stringify(n)||"{}",r=-1,t=m.playabilityStatus;t&&(a.player.va("onHeartbeat",t),"OK"===t.status?r=m.stopHeartbeat?2:0:"UNPLAYABLE"===t.status?r=1:"LIVE_STREAM_OFFLINE"===
t.status&&(r=0));m=r;a.sequenceNumber&&-1===m||a.I.reset();a.sequenceNumber++;BGa(a,n,p,m)}},
onError:function(m){F3(a)&&J3(a,!0,"net-"+m.status)},
onTimeout:function(){F3(a)&&J3(a,!0,"timeout")}};
g.gJ(c)&&(b.QB="Bearer "+g.gJ(c));g.Qp(a.U,"player/heartbeat",d,b)},BGa=function(a,b,c,d){-1===d?(b="decode "+g.uf(c),J3(a,!1,b)):2===d?(K3(a),a.F=!0):(a.N=0,a.B.stop(),1===d?(a.F=!1,a.player.Nf("heartbeat.stop",a.Ke(c)),g.Or("heartbeatActionPlayerHalted",CGa(b))):(a.F=!0,c=0,a.C&&b&&(c=yGa(a,b),a.player.V("livestatedata",b)),c?I3(a,c):I3(a)))},yGa=function(a,b){var c,d=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,e=!(!d||!d.switchStreamsImmediately),f=DGa(d),h=a.getVideoData(),
l=a.player.Va(a.getPlayerType());
if(l.Hb()&&!g.VI(h)&&!a.player.isAtLiveHead(a.getPlayerType())&&!e)return f;e=d&&d.streamTransitionEndpoint&&d.streamTransitionEndpoint.watchEndpoint;if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===(d&&d.transitionTiming))a.getVideoData().BD=e;else{var m;if(m=e)(m=e&&e.videoId)?(a.player.Ji(m,void 0,void 0,!0,!0,e),a.wu("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",b),m=!0):m=!1;if(m)return f}if("OK"===b.status.toUpperCase()){e=d&&d.broadcastId;
m=a.u&&a.u.liveStreamability&&a.u.liveStreamability.liveStreamabilityRenderer&&a.u.liveStreamability.liveStreamabilityRenderer.broadcastId;var n=e!==m&&(null!=e||a.player.Y("web_player_heartbeat_undefined_killswitch"));if(!h.hlsvp&&!h.ga||n)return d={video_id:h.videoId},h.cB&&(d.is_live_destination="1"),a.player.Y("web_player_heartbeat_request_watch_next")||(d.disable_watch_next=!0,d.raw_watch_next_response=h.watchNextResponse),d.autonav_state=h.autonavState,d.oauth_token=h.oauthToken,d.yj=h.yj,8===
a.player.getPresentingPlayerType()&&a.player.hm(8),l=void 0,h.hlsvp||h.ga?n&&(l=new E3("broadcastIdChanged",m+","+e),a.wu("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",b)):(l=new E3("formatsReceived",""+e),a.wu("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",b)),a.player.loadVideoByPlayerVars(d,void 0,void 0,void 0,l),f;a.player.Yc("heartbeat",a.getPlayerType())}d&&d.displayEndscreen&&(a.offlineSlate?
(h=a.offlineSlate,h.I=!0,h.bb&&h.api.Pn()):g.$K(l)&&(h=(null===(c=a.player.dd())||void 0===c?void 0:c.qb())||{},a.player.La("hbse",g.zB(h),!0),a.player.Pn(),a.player.va("onLiveMediaEnded",b)));return f},DGa=function(a){var b=0;
a&&a.pollDelayMs&&(a=Number(a.pollDelayMs))&&(b=a);return b},J3=function(a,b,c){if(!a.B.isActive()){a.B.stop();
a.N++;var d=a.getVideoData();if(d.PG||b&&!g.RI(a.getVideoData())&&!H3(a)&&d.isLivePlayback)var e=!1;else{var f;(null===(e=a.heartbeatParams)||void 0===e?0:e.ys)?f=a.heartbeatParams.ys:f=d.KG||5;e=a.N>=f}e?(b?(b="heartbeat.net",e={enforcedPolicyToHaltOnNetworkFailure:!0}):(b="heartbeat.servererror",e=CGa()),g.Or("heartbeatActionPlayerHalted",e),(e=a.getVideoData())&&e.isLivePlayback?a.player.Nf(b,"\ub3d9\uc601\uc0c1 \uc7ac\uc0dd\uc774 \uc911\ub2e8\ub418\uc5c8\uc2b5\ub2c8\ub2e4. \ub2e4\uc2dc \uc2dc\ub3c4\ud574 \uc8fc\uc138\uc694.",
c):a.player.Nf(b,"\ub3d9\uc601\uc0c1\uc5d0 \ub77c\uc774\uc120\uc2a4\ub97c \ubd80\uc5ec\ud558\ub294 \uc911\uc5d0 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4.",c)):(I3(a,a.I.getValue()),g.Kn(a.I))}},CGa=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},K3=function(a){a.N=0;
a.B.stop();a.F=!1;a.sequenceNumber=0},xGa=function(a){var b=a.getVideoData(),c=a.player.S();
if(b.isLivePlayback)if(g.PC(c.D)){a.C=!0;a.K=!0;if(!g.CD(c)||g.QD(c))a.offlineSlate=new C3(a.player),g.C(a,a.offlineSlate),g.WN(a.player,a.offlineSlate.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(a.u=b.playabilityStatus);a.u?(b=DGa(a.u.liveStreamability&&a.u.liveStreamability.liveStreamabilityRenderer))?I3(a,b):I3(a,7500):I3(a,1E3)}else a.player.Nf("html5.unsupportedlive","HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");else!g.P(c.experiments,"html5_release_post_live_heartbeat_killswitch")&&
g.gb(b.W,"heartbeat")&&a.player.Yc("heartbeat",a.getPlayerType())},zGa=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}},L3={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
L3={ERAS:["BC","AD"],ERANAMES:["\uae30\uc6d0\uc804","\uc11c\uae30"],NARROWMONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),STANDALONENARROWMONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),MONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),STANDALONEMONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),
SHORTMONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),STANDALONESHORTMONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),WEEKDAYS:"\uc77c\uc694\uc77c \uc6d4\uc694\uc77c \ud654\uc694\uc77c \uc218\uc694\uc77c \ubaa9\uc694\uc77c \uae08\uc694\uc77c \ud1a0\uc694\uc77c".split(" "),STANDALONEWEEKDAYS:"\uc77c\uc694\uc77c \uc6d4\uc694\uc77c \ud654\uc694\uc77c \uc218\uc694\uc77c \ubaa9\uc694\uc77c \uae08\uc694\uc77c \ud1a0\uc694\uc77c".split(" "),
SHORTWEEKDAYS:"\uc77c\uc6d4\ud654\uc218\ubaa9\uae08\ud1a0".split(""),STANDALONESHORTWEEKDAYS:"\uc77c\uc6d4\ud654\uc218\ubaa9\uae08\ud1a0".split(""),NARROWWEEKDAYS:"\uc77c\uc6d4\ud654\uc218\ubaa9\uae08\ud1a0".split(""),STANDALONENARROWWEEKDAYS:"\uc77c\uc6d4\ud654\uc218\ubaa9\uae08\ud1a0".split(""),SHORTQUARTERS:["1\ubd84\uae30","2\ubd84\uae30","3\ubd84\uae30","4\ubd84\uae30"],QUARTERS:["\uc81c 1/4\ubd84\uae30","\uc81c 2/4\ubd84\uae30","\uc81c 3/4\ubd84\uae30","\uc81c 4/4\ubd84\uae30"],AMPMS:["\uc624\uc804",
"\uc624\ud6c4"],DATEFORMATS:["y\ub144 M\uc6d4 d\uc77c EEEE","y\ub144 M\uc6d4 d\uc77c","y. M. d.","yy. M. d."],TIMEFORMATS:["a h\uc2dc m\ubd84 s\ucd08 zzzz","a h\uc2dc m\ubd84 s\ucd08 z","a h:mm:ss","a h:mm"],DATETIMEFORMATS:["{1} {0}","{1} {0}","{1} {0}","{1} {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};g.k=x3.prototype;g.k.IC=L3.FIRSTDAYOFWEEK;g.k.KC=L3.FIRSTWEEKCUTOFFDAY;g.k.clone=function(){var a=new x3(this.date);a.IC=this.IC;a.KC=this.KC;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.add=function(a){if(a.B||a.u){var b=this.getMonth()+a.u+12*a.B,c=this.getFullYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.date.setDate(1);this.date.setFullYear(c);this.date.setMonth(b);this.date.setDate(d)}a.days&&(a=new Date((new Date(this.getFullYear(),this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.date.setDate(1),this.date.setFullYear(a.getFullYear()),
this.date.setMonth(a.getMonth()),this.date.setDate(a.getDate()),w3(this,a.getDate()))};
g.k.toString=function(){return[this.getFullYear(),kGa(this.getMonth()+1),kGa(this.getDate())].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};g.u(y3,g.NO);y3.prototype.hide=function(){this.u&&this.u.removeAttribute("aria-haspopup");g.NO.prototype.hide.call(this)};
y3.prototype.show=function(){this.u&&this.u.setAttribute("aria-haspopup","true");g.NO.prototype.show.call(this)};
y3.prototype.ca=function(){g.cg(this.C);g.NO.prototype.ca.call(this)};g.u(z3,g.U);
z3.prototype.I=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.C(a.toggledServiceEndpoint):this.C(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;A3(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.u&&this.u.bb)this.u.jb();else{var b=rGa(this);b&&this.C(b.serviceEndpoint||b.command);b=g.q(b&&b.command&&b.command.commandExecutorCommand&&b.command.commandExecutorCommand.commands||[]);for(var c=b.next();!c.done;c=b.next())if((c=c.value)&&c.openPopupAction&&
c.openPopupAction.popup&&c.openPopupAction.popup.menuPopupRenderer){a=c.openPopupAction.popup.menuPopupRenderer;break}this.u||(this.u=new y3(this.J,this.F),this.u.fa(this.element),g.C(this,this.u),this.u.subscribe("reminderMenuItemClicked",this.C,this));b=this.u;b.menuPopupRenderer=a;pGa(b)}};
z3.prototype.C=function(a){if(a&&(a.addUpcomingEventReminderEndpoint||a.removeUpcomingEventReminderEndpoint)){if(a.addUpcomingEventReminderEndpoint){var b=a.addUpcomingEventReminderEndpoint;var c="notification/add_upcoming_event_reminder"}else a.removeUpcomingEventReminderEndpoint&&(b=a.removeUpcomingEventReminderEndpoint,c="notification/remove_upcoming_event_reminder");if(c&&b&&b.params)for(tGa(this,c,b.params),a=g.q(b.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&b.updateUpcomingEventReminderButtonStateCommand){this.B=
b.updateUpcomingEventReminderButtonStateCommand.state;A3(this);break}}};g.u(C3,g.U);g.k=C3.prototype;g.k.getPlayerType=function(){if(8===this.api.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.na=function(a){var b=a&&a.liveStreamability&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate;if(b){this.u=a;b=b.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.LH():D3(this,b);var c=a&&a.liveStreamability&&a.liveStreamability.liveStreamabilityRenderer&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer.thumbnail;
if(c){var d=0,e=null;c=c.thumbnails;for(var f=0;f<c.length;f++)c[f].width>d&&(d=c[f].width||0,e=c[f].url);e&&(this.background.style.backgroundImage="url("+e+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.B||(this.B=new z3(this.api),this.B.fa(this.ha("ytp-offline-slate-buttons")),g.C(this,this.B)),qGa(this.B,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.B&&qGa(this.B,null,null);this.u=a}else this.u=null;this.OH()};
g.k.OH=function(a){if(8===this.api.getPresentingPlayerType())var b=!0;else{var c=this.api.Va(),d=this.getVideoData();b=d.isLivePlayback&&(g.$K(c)||g.T(c,2)||g.T(c,64));var e=2===d.autonavState&&g.T(c,2);c=c.Hb()&&!g.VI(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.u&&"LIVE_STREAM_OFFLINE"===this.u.status.toUpperCase()||this.api.Y("web_player_pve_client")?this.bb?a&&g.aK(a,2)&&(g.xn(this.element,"ytp-offline-slate-collapsed"),this.C.stop(),g.xn(this.D,"ytp-offline-slate-bar-fade"),this.F.start()):
(a=8===this.api.getPresentingPlayerType(),g.K(this.element,"ytp-offline-slate-premiere-trailer",a),this.show(),this.C.start(),this.api.V("offlineslatestatechange"),this.I&&this.api.Pn()):this.bb&&(this.hide(),this.api.V("offlineslatestatechange"))};
g.k.LH=function(){var a=this.u&&this.u.liveStreamability&&this.u.liveStreamability.liveStreamabilityRenderer&&this.u.liveStreamability.liveStreamabilityRenderer.offlineSlate&&this.u.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer;if(a){var b=Math.floor(g.A()/1E3),c=a.canShowCountdown&&Number(a.scheduledStartTime);!c||c<=b?(D3(this,a),this.countdownTimer.stop()):(b=g.DM(c-b),D3(this,a,b),g.pn(this.countdownTimer))}};
g.k.ca=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.U.prototype.ca.call(this)};E3.prototype.B=function(a){return this.trigger&&a.trigger?this.trigger===a.trigger&&this.u===a.u:!1};
E3.prototype.isExpired=function(){return 3E4<(0,g.M)()-this.C};
E3.prototype.toString=function(){return"heartbeat:"+this.trigger+":"+this.u};g.u(G3,g.hO);g.k=G3.prototype;g.k.ca=function(){K3(this);this.player.Qe("heartbeat");g.hO.prototype.ca.call(this)};
g.k.yd=function(){this.K=!0;I3(this,2E3)};
g.k.GL=function(a){this.heartbeatParams=a;I3(this,2E3)};
g.k.HL=function(a){8!==this.player.getPresentingPlayerType()&&(g.T(a.state,2)||g.T(a.state,64)?(K3(this),this.C&&(this.K=!0,I3(this,1E3))):(g.T(a.state,1)||g.T(a.state,8))&&I3(this,2E3))};
g.k.IL=function(){3!==this.player.getPresentingPlayerType()&&I3(this,2E3)};
g.k.getPlayerType=function(){if(8===this.player.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.Ai=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.wu=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.Or("heartbeatActionPlayerTransitioned",a)};
g.k.Ke=function(a){var b="LICENSE",c=zGa(a);if(c)return c.reason||g.HO[b]||"";(a=a.match(AGa))&&(a=Number(a[1]))&&(b=g.Zka(a));return g.HO[b]||""};
g.k.Dr=function(){return!!this.offlineSlate&&this.offlineSlate.bb};
var AGa=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.nO.heartbeat=G3;})(_yt_player);
